# Generated by Django 5.2.5 on 2025-08-11 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('vehicule', models.CharField(blank=True, max_length=50)),
                ('immatriculation', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeuilleDeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='En cours', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.chauffeur')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_commande', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livré'), ('probleme', 'Problème')], default='en_cours', max_length=20)),
                ('preuve_photo', models.ImageField(blank=True, null=True, upload_to='preuves/')),
                ('signature_client', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.client')),
                ('feuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='livraison.feuillederoute')),
            ],
        ),
    ]
