# Generated by Django 5.2.5 on 2025-08-11 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuillederoute',
            name='date_route',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='last_position_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='horaire_estime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_route', 'En route'), ('terminee', 'Terminée'), ('probleme', 'Problème')], default='planifie', max_length=20),
        ),
    ]
