# Generated by Django 5.2.5 on 2025-08-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_feuillederoute_date_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('actif', models.BooleanField(default=True, verbose_name='Produit actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du sac')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacite', models.CharField(blank=True, max_length=50, verbose_name='Capacité')),
                ('couleur', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('actif', models.BooleanField(default=True, verbose_name='Sac actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Sac',
                'verbose_name_plural': 'Sacs',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'verbose_name': 'Chauffeur', 'verbose_name_plural': 'Chauffeurs'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='feuillederoute',
            options={'verbose_name': 'Feuille de route', 'verbose_name_plural': 'Feuilles de route'},
        ),
        migrations.AlterModelOptions(
            name='livraison',
            options={'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AddField(
            model_name='livraison',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes de livraison'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.chauffeur', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='date_route',
            field=models.DateField(blank=True, null=True, verbose_name='Date de route'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='last_position_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière position'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_route', 'En route'), ('terminee', 'Terminée'), ('probleme', 'Problème')], default='planifie', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='feuille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='livraison.feuillederoute', verbose_name='Feuille de route'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='horaire_estime',
            field=models.TimeField(blank=True, null=True, verbose_name='Horaire estimé'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='preuve_photo',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/', verbose_name='Preuve photo'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='reference_commande',
            field=models.CharField(max_length=50, verbose_name='Référence commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='signature_client',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature client'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livré'), ('probleme', 'Problème')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='produits',
            field=models.ManyToManyField(blank=True, to='livraison.produit', verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='sacs',
            field=models.ManyToManyField(blank=True, to='livraison.sac', verbose_name='Sacs'),
        ),
    ]
