# Generated by Django 5.2.5 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_produit_sac_alter_chauffeur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du véhicule')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('annee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('couleur', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('capacite', models.CharField(blank=True, max_length=50, verbose_name='Capacité')),
                ('actif', models.BooleanField(default=True, verbose_name='Véhicule actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['marque', 'modele'],
            },
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='immatriculation',
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='observations_chauffeur',
            field=models.TextField(blank=True, verbose_name='Observations du chauffeur'),
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='date_observations',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date des observations'),
        ),
        migrations.AddField(
            model_name='feuillederoute',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison.vehicule', verbose_name='Véhicule assigné'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='signature_tactile',
            field=models.TextField(blank=True, verbose_name='Signature tactile (SVG)'),
        ),
    ]
